<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Emby Live TV tuner plugin for non-DRM Zattoo streams.</Description>
    <AssemblyName>Emby.Zattoo</AssemblyName>
    <RootNamespace>Emby.Zattoo.Plugin</RootNamespace>
    <Version>0.2.4</Version>
    <AssemblyVersion>0.2.4.0</AssemblyVersion>
    <FileVersion>0.2.4.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Pipelines" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Memory" Version="4.6.3">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile
      Include="../Emby.Zattoo.Core/**/*.cs"
      Exclude="../Emby.Zattoo.Core/bin/**/*.cs;../Emby.Zattoo.Core/obj/**/*.cs"
      Link="Core/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <Target Name="CreatePluginPackage" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <PropertyGroup>
      <PluginPackageDirectory>$(MSBuildProjectDirectory)/../../artifacts/Emby.Zattoo</PluginPackageDirectory>
    </PropertyGroup>
    <RemoveDir Directories="$(PluginPackageDirectory)" />
    <MakeDir Directories="$(PluginPackageDirectory)" />
    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFolder="$(PluginPackageDirectory)" />
  </Target>
</Project>
